version: 0.2

phases:
  build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 626635443051.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Building the Docker image for frontend"
      - docker build -t my-frontend ./frontend
      - docker tag my-frontend:latest 626635443051.dkr.ecr.ap-south-1.amazonaws.com/my-frontend:latest
      - echo "Pushing the Docker image to ECR"
      - docker push 626635443051.dkr.ecr.ap-south-1.amazonaws.com/my-frontend:latest

artifacts:
  files:
    - "**/*"
