# Generated by Django 5.1 on 2024-09-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(blank=True, choices=[('attending', 'Attending'), ('not attending', 'Not Attending'), ('maybe', 'Maybe'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
