# Generated by Django 5.1 on 2024-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_guestlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='status',
            field=models.CharField(choices=[('attending', 'Attending'), ('not attending', 'Not Attending'), ('maybe', 'Maybe'), ('checked_in', 'Checked In')], default='attending', max_length=20),
        ),
    ]
