# Generated by Django 5.1 on 2024-09-30 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
        ('rsvp', '0004_alter_guestlist_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guestlist',
            index=models.Index(fields=['event'], name='rsvp_guestl_event_i_1c95f3_idx'),
        ),
        migrations.AddIndex(
            model_name='guestlist',
            index=models.Index(fields=['status'], name='rsvp_guestl_status_381e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='guestlist',
            index=models.Index(fields=['guest_name'], name='rsvp_guestl_guest_n_8be908_idx'),
        ),
    ]
